files:
  include: 'source/**/*.scss'
rules:
  indentation: [0]
  brace-style: [0]
  leading-zero: [0]
  nesting-depth: [0]
  class-name-format: [0]
  property-sort-order: [0]
  force-pseudo-nesting: [0]
  variable-name-format: [0]
  force-element-nesting: [0]
  no-qualifying-elements: [0]
  force-attribute-nesting: [0]
  empty-line-between-blocks: [0]
  no-vendor-prefixes: [0]
  no-color-literals: [0]
  no-invalid-hex: [0]
  no-important: [0]
  no-ids: [0]
