language: node_js
node_js: 8
env:
  - WEXT_SHIPIT_CHROME_EXTENSION_ID=pieemlagbhnombolehnjdoaoojpphedd
script:
  - npm run lint
  - npm run build
deploy:
  skip_cleanup: true
  provider: script
  script: npm run release
  on:
    branch: master
    condition: $(npm run can-release --silent)
cache:
  directories:
    - ~/.npm
    - node_modules
